language: java
jdk:
  - openjdk6
  - oraclejdk8
after_success:
  - ./gradlew jacocoTestReport coveralls

deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew bintrayUpload
  on:
    branch: production
